// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1289.stronghold.subsystems;

import org.usfirst.frc1289.stronghold.RobotMap;

import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;


import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class BallHandler extends Subsystem {

    private final SpeedController ballMotorL = RobotMap.ballHandlerBallMotorL;
    private final SpeedController ballMotorR = RobotMap.ballHandlerBallMotorR;
    private final AnalogInput BallSwitch = RobotMap.ballHandlerSwitch;
    private final Solenoid ballsolenoid = RobotMap.ballHandlerBallsolenoid;
    private final Solenoid BallShooter = RobotMap.BallShooter;
    private boolean HandlerUp;
 
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
  
    }
  
	public void moveball (double speed){
		  ballMotorL.set(-speed);
		  ballMotorR.set(speed);
	}
  
	public double getSwitch()  {
		return BallSwitch.getVoltage();
	}
 
 	public void ballPneu (boolean direction){
 		HandlerUp = !direction;
 		ballsolenoid.set(!direction);
 		//SmartDashboard.putBoolean("Handler Up", HandlerUp);
 	}
 	
 	public boolean HandlerState () {
 		return HandlerUp;
 	}
	public void PushBallOut (boolean direction){
		
		//remove line below when using real robot
		//if (direction) spneumatic.set(DoubleSolenoid.Value.kForward);  else spneumatic.set(DoubleSolenoid.Value.kReverse);
		//restore code below when using real robot
		BallShooter.set(direction);
		
	}
}




