// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1289.stronghold.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc1289.stronghold.Robot;

/**
 *
 */
public class BallShoot extends Command {

    Timer BallShootTime;
    
    public BallShoot() {
        requires(Robot.ballShooter);

    }

    // Called just before this Command runs the first time
    protected void initialize() {
   	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if(Robot.ballShooter.BallShooterState())
    	{
    		Robot.ballShooter.shootball(0.0);
    	}
    	else
    	{    	
    		Robot.ballShooter.shootball(1.0);
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return true; //Run Once
    }

    // Called once after isFinished returns true
    protected void end() {
    	//Robot.ballShooter.shootball(0.0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
