// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1289.stronghold.subsystems;

import org.usfirst.frc1289.stronghold.RobotMap;

import edu.wpi.first.wpilibj.SpeedController;


import edu.wpi.first.wpilibj.command.Subsystem;
//import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class BallShooter extends Subsystem {

    private final SpeedController ballMotorL = RobotMap.ballShooter1;
    private final SpeedController ballMotorR = RobotMap.ballShooter2;
 
    private boolean shooterOn;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
  
    }
  
	public void shootball (double speed){
		  ballMotorL.set(-speed);
		  ballMotorR.set(speed);
		  
		  if (speed == 0.0)
		  {
			  	shooterOn = false;		  
		  }
		  else
		  {
			  shooterOn = true;			  
		  }
	}
	
    public boolean BallShooterState (){
    	return shooterOn;
    }
}




