// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1289.stronghold.subsystems;

import org.usfirst.frc1289.stronghold.RobotMap;
import org.usfirst.frc1289.stronghold.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {


    private final SpeedController motorLeft = RobotMap.driveTrainMotorLeft;
    private final SpeedController motorRight = RobotMap.driveTrainMotorRight;
    private final RobotDrive robotDrive21 = RobotMap.driveTrainRobotDrive21;

    
    public void initDefaultCommand() {

        setDefaultCommand(new DriveWithJoystick());

    }
    
    public void ArcadeDrive (Joystick stick){
    	
    	double x,y;
    	
    	// Get the Joystick X and Y values
    	x=stick.getX();
    	y=-stick.getY();
    	
    	// Test the trigger button. If pressed then cut the value of X and Y by half
    	if (stick.getRawButton(1)) {
    		x=x*1;
    		y=y*1;
    	}

    	else{
    		
    		x=x*.75;
    		y=y*.75;
    	}
    	// Send the final X and Y value to the arcade drive to set the motor speed.
    	robotDrive21.arcadeDrive(x,y);
   }

    

    // Sets the motor speed of all motors to the desired setting
    public void moverobot (double speed){
    	motorLeft.set(speed);
    	motorRight.set(speed);
    }

    // Sets the motor speed in opposite directions so robot turns
    public void turnrobot(double speed) {
    	motorLeft.set(speed);
    	motorRight.set(-speed);
    }


}

