// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1289.stronghold;

import edu.wpi.first.wpilibj.Jaguar;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Servo;

import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Victor;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
//import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    
    //static final double kToleranceDegrees = 2.0f;
    
	public static Servo ballIndexer;						// PWM 4
	
    public static SpeedController ballShooter1;				// PWM 3
    public static SpeedController ballShooter2;				// PWM 2
    public static SpeedController driveTrainMotorRight;		// PWM 1
    public static SpeedController driveTrainMotorLeft;		// PWM 0
    
    public static RobotDrive driveTrainRobotDrive21;
    
    
    


    public static void init() {
        
      
        ballIndexer = new Servo(4);
        
        
        ballShooter1 = new Victor(2);
        LiveWindow.addActuator("Ball Shooter", "Shooter 1", (Victor) ballShooter1);
        ballShooter2 = new Victor(3);
        LiveWindow.addActuator("Ball Shooter", "Shooter 2", (Victor) ballShooter2);
        
        driveTrainMotorLeft = new Jaguar(0);
        driveTrainMotorRight = new Jaguar(1);

      
     
        driveTrainRobotDrive21 = new RobotDrive(driveTrainMotorLeft, driveTrainMotorRight);
        
        driveTrainRobotDrive21.setSafetyEnabled(true);
        driveTrainRobotDrive21.setExpiration(0.1);
        driveTrainRobotDrive21.setSensitivity(0.5);
        driveTrainRobotDrive21.setMaxOutput(1.0);

        driveTrainRobotDrive21.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        //driveTrainRobotDrive21.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        //driveTrainRobotDrive21.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        
    
    }
}


 

